const REGIONS={US:{base:"https://www.apple.com",suffix:"LL"},CA:{base:"https://www.apple.com/ca",suffix:"VC"},GB:{base:"https://www.apple.com/uk",suffix:"B"},AU:{base:"https://www.apple.com/au",suffix:"X"}};
export const PRODUCT_CATALOG=[
{id:"iphone-18-pro",name:"iPhone 18 Pro",slug:"iphone-18-pro"},
{id:"iphone-18-pro-max",name:"iPhone 18 Pro Max",slug:"iphone-18-pro"},
{id:"iphone-17",name:"iPhone 17",slug:"iphone-17"},
{id:"ipad",name:"iPad",slug:"ipad"},
{id:"macbook-pro",name:"MacBook Pro",slug:"macbook-pro"}
];
export const publicCatalog=()=>PRODUCT_CATALOG.map(({id,name})=>({id,name,configurations:[{name:"Automatic — choose from Apple",index:0}]}));
const uniq=a=>[...new Set(a.filter(Boolean))];
function walk(v,out=[]){if(!v)return out;if(Array.isArray(v)){for(const x of v)walk(x,out);return out}if(typeof v==="object"){for(const [k,x] of Object.entries(v)){if(/part|sku/i.test(k)&&typeof x==="string")out.push(x);walk(x,out)}}return out}
function validPart(v){return /^[A-Z0-9]{5,14}[A-Z0-9]*\/[A-Z]$/.test(String(v||"").toUpperCase())}
function titleFromStoreData(stores,part){for(const s of stores||[]){const a=s?.partsAvailability?.[part];const t=a?.messageTypes?.regular?.storePickupProductTitle||a?.messageTypes?.sticky?.storePickupProductTitle;if(t)return t}return part}
function modelMatchesTitle(product,title){const t=String(title||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim(),name=product.name.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();if(product.id==="iphone-18-pro-max")return t.includes(name);if(product.id==="iphone-18-pro")return t.includes(name)&&!t.includes("iphone 18 pro max");if(product.id==="iphone-17")return t.includes(name);return true}\nexport async function discoverAppleConfigurations({productId,country="US",location}){const product=PRODUCT_CATALOG.find(p=>p.id===String(productId||""));if(!product)throw Error("Unknown model.");const region=REGIONS[country]||REGIONS.US,urls=[`${region.base}/shop/buy-iphone/${product.slug}`,`${region.base}/shop/buy-ipad/${product.slug}`,`${region.base}/shop/buy-mac/${product.slug}`];let html="";for(const url of urls){const r=await fetch(url,{headers:{"user-agent":"Mozilla/5.0","accept":"text/html"}});if(r.ok){html=await r.text();if(html.length>1000)break}}if(!html)throw Error("Could not load Apple's product page.");let candidates=uniq((html.match(/[A-Z0-9]{5,14}\/[A-Z]/g)||[]).map(x=>x.toUpperCase()));try{for(const m of html.matchAll(/<script[^>]*type=["']application\/json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{candidates.push(...walk(JSON.parse(m[1])).map(x=>String(x).toUpperCase()))}catch{}}}catch{}candidates=uniq(candidates.filter(validPart)).slice(0,80);if(!candidates.length)throw Error("Apple's product page did not expose inventory identifiers.");const q=new URLSearchParams({pl:"true",location:String(location||"")});candidates.forEach((p,i)=>q.set(`parts.${i}`,p));const rr=await fetch(`${region.base}/shop/retail/pickup-message?${q}`,{headers:{accept:"application/json,text/plain,*/*"}});if(!rr.ok)throw Error(`Apple inventory discovery returned HTTP ${rr.status}.`);const data=await rr.json(),stores=data?.body?.stores||[];const recognized=uniq(stores.flatMap(s=>Object.keys(s?.partsAvailability||{}))).filter(p=>candidates.includes(p));const wanted=recognized.map(part=>({part,name:titleFromStoreData(stores,part),productUrl:urls[0]})).filter(x=>modelMatchesTitle(product,x.name));return{product,configurations:(wanted.length?wanted:recognized.map(part=>({part,name:titleFromStoreData(stores,part),productUrl:urls[0]}))).slice(0,40)}}