import{sendPushNotification}from"@mmmike/web-push/send";import{checkPickupInventory,InventoryError,locationKey,parseLocationKey}from"./inventory.js";import{publicCatalog,discoverAppleConfigurations}from"./catalog.js";
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}}),body=async r=>{try{return await r.json()}catch{return{}}},parse=v=>{try{return JSON.parse(v||"[]")}catch{return[]}},safe=w=>({id:w.id,label:w.label,location:w.location,status:w.status,stores:parse(w.stores_json),productUrl:w.product_url||"",lastCheckedAt:w.last_checked_at,lastError:w.last_error});
async function push(env,deviceId,payload){if(!env.VAPID_PUBLIC_KEY||!env.VAPID_PRIVATE_KEY)throw Error("Push is not configured.");const row=await env.DB.prepare("SELECT subscription_json FROM subscriptions WHERE device_id=?").bind(deviceId).first();if(!row)return false;const ok=await sendPushNotification(JSON.parse(row.subscription_json),payload,{publicKey:env.VAPID_PUBLIC_KEY,privateKey:env.VAPID_PRIVATE_KEY,subject:env.VAPID_SUBJECT||"mailto:admin@example.com"},{ttl:300,urgency:"high"});if(!ok)await env.DB.prepare("DELETE FROM subscriptions WHERE device_id=?").bind(deviceId).run();return ok}
async function updateWatchInventory(env,w,stores,checkedAt,error=null){
  const nearest=(stores||[]).slice(0,12);
  if(!nearest.length){await env.DB.prepare("UPDATE watches SET status='unknown',stores_json='[]',last_checked_at=?,last_error=? WHERE id=?").bind(checkedAt,error||"No inventory data returned.",w.id).run();return}
  const available=nearest.filter(s=>s.available),unknown=nearest.filter(s=>s.inventoryState==="unknown"),now=available.length>0,state=now?"available":unknown.length?"unknown":"unavailable";let notified=+w.notified_available||0;
  if(now&&w.status!=="available"&&!notified){try{const names=available.slice(0,3).map(s=>s.storeName).join(", ");await push(env,w.device_id,{title:`${w.label} is in stock`,body:`${names}. Tap to buy from Apple.`,url:w.product_url||"/"});notified=1}catch(e){console.log(e.message)}}else if(state==="unavailable")notified=0;
  await env.DB.prepare("UPDATE watches SET status=?,stores_json=?,last_checked_at=?,last_error=?,notified_available=? WHERE id=?").bind(state,JSON.stringify(nearest),checkedAt,error,notified,w.id).run()
}
async function checkLocation(env,key,force=false){
  if(!force){const b=await env.DB.prepare("SELECT until_ms FROM location_backoff WHERE location=?").bind(key).first();if(b&&+b.until_ms>Date.now())return}
  const rows=(await env.DB.prepare("SELECT * FROM watches WHERE location=?").bind(key).all()).results||[];if(!rows.length)return;
  const apple=rows.filter(w=>!String(w.part).startsWith("RETAIL:"));
  if(apple.length)try{
    const inv=await checkPickupInventory({parts:[...new Set(apple.map(w=>w.part))],location:key});
    for(const w of apple)await updateWatchInventory(env,w,inv.byPart[w.part]||[],inv.checkedAt);
    await env.DB.prepare("DELETE FROM location_backoff WHERE location=?").bind(key).run()
  }catch(e){
    if(e.status===429||e.status===541)await env.DB.prepare("INSERT INTO location_backoff(location,until_ms) VALUES(?,?) ON CONFLICT(location) DO UPDATE SET until_ms=excluded.until_ms").bind(key,Date.now()+600000).run();
    for(const w of apple)await env.DB.prepare("UPDATE watches SET last_error=? WHERE id=?").bind(e.message,w.id).run()
  }
}
async function api(req,env,u){const p=u.pathname;if(p==="/api/health")return json({ok:true});if(p==="/api/config")return json({pushConfigured:!!(env.VAPID_PUBLIC_KEY&&env.VAPID_PRIVATE_KEY),vapidPublicKey:env.VAPID_PUBLIC_KEY||"",checkIntervalMs:+env.CHECK_INTERVAL_MS||60000});if(p==="/api/catalog")return json({products:publicCatalog()});if(p==="/api/discover"&&req.method==="POST"){const b=await body(req);try{const d=await discoverAppleConfigurations({productId:b.catalogProductId,country:String(b.country||"US").toUpperCase(),location:b.location});return json({product:{id:d.product.id,name:d.product.name},configurations:d.configurations})}catch(e){return json({error:e.message},502)}}
if(p==="/api/stores"&&req.method==="POST"){const b=await body(req),part=String(b.part||"").toUpperCase();if(!part)return json({error:"Choose a configuration first."},400);try{const inv=await checkPickupInventory({parts:[part],location:b.location,country:String(b.country||"US").toUpperCase()});return json({stores:(inv.byPart[part]||[]).slice(0,12),checkedAt:inv.checkedAt})}catch(e){return json({error:e.message},502)}}
if(p==="/api/watches"&&req.method==="GET"){const id=u.searchParams.get("deviceId");const r=await env.DB.prepare("SELECT * FROM watches WHERE device_id=? AND part NOT LIKE 'RETAIL:%' ORDER BY created_at DESC").bind(id).all();return json((r.results||[]).map(safe))}
if(p==="/api/subscriptions"&&req.method==="POST"){const b=await body(req);if(!b.deviceId||!b.subscription?.endpoint)return json({error:"Invalid subscription."},400);await env.DB.prepare("INSERT INTO subscriptions(device_id,subscription_json,updated_at) VALUES(?,?,?) ON CONFLICT(device_id) DO UPDATE SET subscription_json=excluded.subscription_json,updated_at=excluded.updated_at").bind(b.deviceId,JSON.stringify(b.subscription),new Date().toISOString()).run();return json({ok:true})}
if(p==="/api/watches"&&req.method==="POST"){const b=await body(req),part=String(b.part||"").toUpperCase(),label=String(b.label||"Apple product").slice(0,120);if(!b.deviceId||!b.location||!part)return json({error:"Device, configuration and postal code are required."},400);if(part.startsWith("RETAIL:"))return json({error:"Only iPhone tracking is supported."},400);const key=locationKey(String(b.country||"US").toUpperCase(),b.location),id=crypto.randomUUID();await env.DB.prepare("INSERT INTO watches(id,device_id,label,part,location,radius,product_url,status,stores_json,created_at) VALUES(?,?,?,?,?,9999,?,'pending','[]',?)").bind(id,b.deviceId,label,part,key,String(b.productUrl||""),new Date().toISOString()).run();await checkLocation(env,key,true);return json({ok:true,id},201)}
let m=p.match(/^\/api\/watches\/([^/]+)$/);if(m&&req.method==="DELETE"){const d=u.searchParams.get("deviceId");await env.DB.prepare("DELETE FROM watches WHERE id=? AND device_id=?").bind(m[1],d).run();return json({ok:true})}m=p.match(/^\/api\/check\/([^/]+)$/);if(m&&req.method==="POST"){const b=await body(req),w=await env.DB.prepare("SELECT * FROM watches WHERE id=? AND device_id=?").bind(m[1],b.deviceId).first();if(!w)return json({error:"Watch not found."},404);await checkLocation(env,w.location,true);return json({ok:true})}if(p==="/api/test-push"&&req.method==="POST"){const b=await body(req);try{return await push(env,b.deviceId,{title:"StockPing is ready",body:"Notifications are working.",url:"/"})?json({ok:true}):json({error:"No active push subscription."},404)}catch(e){return json({error:e.message},502)}}return json({error:"Not found"},404)}
export default{async fetch(req,env){const u=new URL(req.url);return u.pathname.startsWith("/api/")?api(req,env,u):env.ASSETS.fetch(req)},async scheduled(c,env,ctx){ctx.waitUntil((async()=>{const r=await env.DB.prepare("SELECT DISTINCT location FROM watches WHERE part NOT LIKE 'RETAIL:%' LIMIT 25").all();for(const x of r.results||[])await checkLocation(env,x.location)})())}};